### ISSUE TITLE
Enhance messaging for what folder is being linted

### ISSUE THREAD

**Issue by Geoffrotism** [ProjectAliceDev/renpy-lint-action#5]
I ran the renpy linter locally and had 80 files linted with some statistics. When run through the github action it says 0. To help with debugging the difference it would be helpful to have a more complete console log. Since the default location is `.` the location prints out `....` which is a little confusing.

![image](https://user-images.githubusercontent.com/5430964/149591212-94ff9292-254f-41ee-a6a1-910745a46df4.png)
 
Something like: 
`Linting the project at <root>/<input>` would be a little more clear 
TBH not sure if the root helps at all with github actions, but removing the trailing ... would be great.

**Comment by alicerunsonfedora** [comment]
The linking message is more from Ren'Py than it is from us.

**Comment by Geoffrotism** [comment]
While true, I was more pointing at the `Linting the project at ....` which I believe is something done by this Github Action:
https://github.com/ProjectAliceDev/renpy-lint-action/blob/4ffb1f6365b80bf43fe65f82fa37126a2e7b30f1/lint.sh#L18

**Comment by alicerunsonfedora** [comment]
I see. While I agree the message may be confusing, I don't think removing the ellipses is the answer. We could, however, add quotes around the directory name in the echo message.

**Comment by alicerunsonfedora** [comment]
Should be resolved in v1.1.2. Changes in master branch
